I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/image gallery/gallery.rpy", line 75, in execute
    screen gallery_B():
  File "game/image gallery/gallery.rpy", line 75, in execute
    screen gallery_B():
  File "game/image gallery/gallery.rpy", line 84, in execute
    grid maxnumx maxnumy:
  File "game/image gallery/gallery.rpy", line 90, in execute
    for i in range(start, end + 1):
  File "game/image gallery/gallery.rpy", line 92, in execute
    if gallery_items[i].is_locked:
  File "game/image gallery/gallery.rpy", line 98, in execute
    imagebutton:
Exception: Not a displayable: ('idleLG', ['cg_sushi_unlock'])

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\python.py", line 1184, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in <module>
    python hide:
  File "renpy/common/_layout/screen_main_menu.rpym", line 35, in _execute_python_hide
    ui.interact()
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\display\core.py", line 2218, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\display\core.py", line 2748, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  [Previous line repeated 1 more time]
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\display\screen.py", line 480, in visit_all
    callback(self)
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\display\core.py", line 2748, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\display\screen.py", line 491, in per_interact
    self.update()
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\display\screen.py", line 700, in update
    self.screen.function(**self.scope)
  File "game/image gallery/gallery.rpy", line 75, in execute
    screen gallery_B():
  File "game/image gallery/gallery.rpy", line 75, in execute
    screen gallery_B():
  File "game/image gallery/gallery.rpy", line 84, in execute
    grid maxnumx maxnumy:
  File "game/image gallery/gallery.rpy", line 90, in execute
    for i in range(start, end + 1):
  File "game/image gallery/gallery.rpy", line 92, in execute
    if gallery_items[i].is_locked:
  File "game/image gallery/gallery.rpy", line 98, in execute
    imagebutton:
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\ui.py", line 982, in _imagebutton
    return renpy.display.behavior.ImageButton(
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\display\behavior.py", line 1249, in __init__
    idle_=renpy.easy.displayable(idle_image),
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\easy.py", line 145, in displayable
    raise Exception("Not a displayable: %r" % (d,))
Exception: Not a displayable: ('idleLG', ['cg_sushi_unlock'])

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.6.25022803
HeartsDepthDEMO 2.5
Tue Aug 12 04:17:55 2025
