I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 133, in script
    Y "Excuse me- sir! Hello?"
Exception: Sayer 'Y' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 133, in script
    Y "Excuse me- sir! Hello?"
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Y' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
DeepSeaDatingSim 1.0
Sun Jun 30 14:57:27 2024
