I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/options.rpy", line 67, in script
    define config.default_sound_volume = 1.0
  File "renpy/common/000namespaces.rpy", line 34, in set
    setattr(self.nso, name, value)
Exception: config.default_sound_volume is not a known configuration variable.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/options.rpy", line 67, in script
    define config.default_sound_volume = 1.0
  File "C:\Users\Alyssa\Documents\renpy-8.3.7-sdk\renpy\ast.py", line 2248, in execute
    self.set()
  File "C:\Users\Alyssa\Documents\renpy-8.3.7-sdk\renpy\ast.py", line 2266, in set
    ns.set(self.varname, value)
  File "renpy/common/000namespaces.rpy", line 34, in set
    setattr(self.nso, name, value)
  File "C:\Users\Alyssa\Documents\renpy-8.3.7-sdk\renpy\defaultstore.py", line 101, in __setattr__
    raise Exception('config.%s is not a known configuration variable.' % (name))
Exception: config.default_sound_volume is not a known configuration variable.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
HeartsDepthDEMO 2.5
Fri Jun 27 14:34:14 2025
